SET hivevar:DAT_RFRC = 202001;
SET hivevar:DTREF_1MS = CAST(CONCAT(YEAR(ADD_MONTHS(CONCAT(SUBSTR(CAST(${DAT_RFRC} AS STRING),1,4),'-',SUBSTR(CAST(${DAT_RFRC} AS STRING),5,2),'-','05'),(-1))),LPAD(MONTH(ADD_MONTHS(CONCAT(SUBSTR(CAST(${DAT_RFRC} AS STRING),1,4),'-',SUBSTR(CAST(${DAT_RFRC} AS STRING),5,2),'-',05),(-1))),2,'0')) AS INT);
-- SET hivevar:DTREF_2MS = CAST(CONCAT(YEAR(ADD_MONTHS(CONCAT(SUBSTR(CAST(${DAT_RFRC} AS STRING),1,4),'-',SUBSTR(CAST(${DAT_RFRC} AS STRING),5,2),'-','05'),(-2))),LPAD(MONTH(ADD_MONTHS(CONCAT(SUBSTR(CAST(${DAT_RFRC} AS STRING),1,4),'-',SUBSTR(CAST(${DAT_RFRC} AS STRING),5,2),'-',05),(-2))),2,'0')) AS INT);
-- SET hivevar:DTREF_3MS = CAST(CONCAT(YEAR(ADD_MONTHS(CONCAT(SUBSTR(CAST(${DAT_RFRC} AS STRING),1,4),'-',SUBSTR(CAST(${DAT_RFRC} AS STRING),5,2),'-','05'),(-3))),LPAD(MONTH(ADD_MONTHS(CONCAT(SUBSTR(CAST(${DAT_RFRC} AS STRING),1,4),'-',SUBSTR(CAST(${DAT_RFRC} AS STRING),5,2),'-',05),(-3))),2,'0')) AS INT);
-- SET hivevar:DTREF_4MS = CAST(CONCAT(YEAR(ADD_MONTHS(CONCAT(SUBSTR(CAST(${DAT_RFRC} AS STRING),1,4),'-',SUBSTR(CAST(${DAT_RFRC} AS STRING),5,2),'-','05'),(-4))),LPAD(MONTH(ADD_MONTHS(CONCAT(SUBSTR(CAST(${DAT_RFRC} AS STRING),1,4),'-',SUBSTR(CAST(${DAT_RFRC} AS STRING),5,2),'-',05),(-4))),2,'0')) AS INT);
-- SET hivevar:DTREF_5MS = CAST(CONCAT(YEAR(ADD_MONTHS(CONCAT(SUBSTR(CAST(${DAT_RFRC} AS STRING),1,4),'-',SUBSTR(CAST(${DAT_RFRC} AS STRING),5,2),'-','05'),(-5))),LPAD(MONTH(ADD_MONTHS(CONCAT(SUBSTR(CAST(${DAT_RFRC} AS STRING),1,4),'-',SUBSTR(CAST(${DAT_RFRC} AS STRING),5,2),'-',05),(-5))),2,'0')) AS INT);
-- SET hivevar:DTREF_6MS = CAST(CONCAT(YEAR(ADD_MONTHS(CONCAT(SUBSTR(CAST(${DAT_RFRC} AS STRING),1,4),'-',SUBSTR(CAST(${DAT_RFRC} AS STRING),5,2),'-','05'),(-6))),LPAD(MONTH(ADD_MONTHS(CONCAT(SUBSTR(CAST(${DAT_RFRC} AS STRING),1,4),'-',SUBSTR(CAST(${DAT_RFRC} AS STRING),5,2),'-',05),(-6))),2,'0')) AS INT);
-- SET hivevar:DTREF_11MS = CAST(CONCAT(YEAR(ADD_MONTHS(CONCAT(SUBSTR(CAST(${DAT_RFRC} AS STRING),1,4),'-',SUBSTR(CAST(${DAT_RFRC} AS STRING),5,2),'-','05'),(-11))),LPAD(MONTH(ADD_MONTHS(CONCAT(SUBSTR(CAST(${DAT_RFRC} AS STRING),1,4),'-',SUBSTR(CAST(${DAT_RFRC} AS STRING),5,2),'-',05),(-11))),2,'0')) AS INT);
-- SET hivevar:DTREF_12MS = CAST(CONCAT(YEAR(ADD_MONTHS(CONCAT(SUBSTR(CAST(${DAT_RFRC} AS STRING),1,4),'-',SUBSTR(CAST(${DAT_RFRC} AS STRING),5,2),'-','05'),(-12))),LPAD(MONTH(ADD_MONTHS(CONCAT(SUBSTR(CAST(${DAT_RFRC} AS STRING),1,4),'-',SUBSTR(CAST(${DAT_RFRC} AS STRING),5,2),'-',05),(-12))),2,'0')) AS INT);
-- SET hivevar:DTREF_13MS = CAST(CONCAT(YEAR(ADD_MONTHS(CONCAT(SUBSTR(CAST(${DAT_RFRC} AS STRING),1,4),'-',SUBSTR(CAST(${DAT_RFRC} AS STRING),5,2),'-','05'),(-13))),LPAD(MONTH(ADD_MONTHS(CONCAT(SUBSTR(CAST(${DAT_RFRC} AS STRING),1,4),'-',SUBSTR(CAST(${DAT_RFRC} AS STRING),5,2),'-',05),(-13))),2,'0')) AS INT);
-- SET hivevar:DTREF_14MS = CAST(CONCAT(YEAR(ADD_MONTHS(CONCAT(SUBSTR(CAST(${DAT_RFRC} AS STRING),1,4),'-',SUBSTR(CAST(${DAT_RFRC} AS STRING),5,2),'-','05'),(-14))),LPAD(MONTH(ADD_MONTHS(CONCAT(SUBSTR(CAST(${DAT_RFRC} AS STRING),1,4),'-',SUBSTR(CAST(${DAT_RFRC} AS STRING),5,2),'-',05),(-14))),2,'0')) AS INT);

SELECT
    *
FROM teste 
WHERE ABC IN (1,2,3) AND DCE = 2;
