SELECT
DIAENC.NUMERO_CLIENTE AS NUMERO_CLIENTE,
DIAENC.CORR_FACTURATION AS CORR_FACTURACION,
NVL(CLI.CLI_GRUPO, 'SEM GRUPO') AS GRUPO,
0 AS COFINS_FAT,
0 AS COFINS_REFAT,
DIAENC.VALOR_ENCARGO AS COFINS_CANC,
from_unixtime(unix_timestamp(DIAENC.DT_CANCELAMENTO,'yyyy-MM-dd'),'yyyyMM') AS IGE_REFERENCIA
FROM BT_ENCARGOS_DIARIO DIAENC
WHERE 
TRIM(FAT.CLASSE) IN ('REBRBPC','REBRIND','REBRMUL','REBRQUI','REBXR','REPLN','RESBOPT','01','1')
;